### ISSUE TITLE
Remove aws signing

### ISSUE THREAD

**Issue by prabhu** [colearnr/colearnr#11]
2016-06-22T14:13:42.744Z - error: Error converting url to signed url https://youtu.be/Y20ZTjgkDrM Error: No key provided to sign
    at Sign.sign (crypto.js:272:11)
    at _createPolicySignature (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:161:15)
    at Object.getSignedUrl (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:23:19)
    at Object.Cloud.getSignedUrl (/home/colearnr/cl/webapp-v1.0.0-alpha1/lib/cloud.js:15:17)
    at Object.query._streamUrlCheck (/home/colearnr/cl/webapp-v1.0.0-alpha1/common/query.js:115:28)

**Comment by prabhu** [comment]
2016-06-22T14:13:42.721Z - error: Error converting url to signed url cl://1c474c1abb4403fb6c27eefeb3c775aa/Creativity.ppt Error: No ke
y provided to sign
    at Sign.sign (crypto.js:272:11)
    at _createPolicySignature (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:161:15)
    at Object.getSignedUrl (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:23:19)
    at Object.Cloud.getSignedUrl (/home/colearnr/cl/webapp-v1.0.0-alpha1/lib/cloud.js:15:17)
    at Object.query._streamUrlCheck (/home/colearnr/cl/webapp-v1.0.0-alpha1/common/query.js:115:28)
    at /home/colearnr/cl/webapp-v1.0.0-alpha1/common/query.js:176:12

**Comment by beekrishna** [comment]
Hi Prabhu

How are you? Hope everything is going well on your side.

I am still looking for a project in electronics city and I am taking much
needed rest.

Let me know if I can help you in colearnr anyway(I am serious this time).

Thanks
Krishna

On Thursday, 23 June 2016, Prabhu <notifications@github.com> wrote:

> 2016-06-22T14:13:42.721Z - error: Error converting url to signed url
> cl://1c474c1abb4403fb6c27eefeb3c775aa/Creativity.ppt Error: No ke
> y provided to sign
> at Sign.sign (crypto.js:272:11)
> at _createPolicySignature
> (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:161:15)
> at Object.getSignedUrl
> (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/aws-cloudfront-sign/lib/cloudfrontUtil.js:23:19)
> at Object.Cloud.getSignedUrl
> (/home/colearnr/cl/webapp-v1.0.0-alpha1/lib/cloud.js:15:17)
> at Object.query._streamUrlCheck
> (/home/colearnr/cl/webapp-v1.0.0-alpha1/common/query.js:115:28)
> at /home/colearnr/cl/webapp-v1.0.0-alpha1/common/query.js:176:12
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/colearnr/colearnr/issues/11#issuecomment-228033592>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ3Eh-d4y2Ap8TX7ybtN-NSwDn72OafGks5qOnrXgaJpZM4I8wFc>
> .
>


-- 
Regards

Krishna Kumar B.

**Comment by prabhu** [comment]
Fixed by https://github.com/colearnr/colearnr/commit/51aef5d479a14b17e553198b291574114c31a207
