### ISSUE TITLE
Unable to create polls anymore

### ISSUE THREAD

**Issue by prabhu** [colearnr/colearnr#9]
Regression with 1.0.0-alpha1

2016-06-23T10:56:36.602Z - error: Unable to load learnbit. Please try after some time. null 529de48f95fdd2956700001d
TypeError: Cannot set property '_val' of undefined
    at create_learn_bit (/home/colearnr/cl/webapp-v1.0.0-alpha1/common/create_learn_bit.js:26:13)
    at save_edit_full (/home/colearnr/cl/webapp-v1.0.0-alpha1/routes/lbits.js:608:5)
    at exports.save_edit_full (/home/colearnr/cl/webapp-v1.0.0-alpha1/routes/lbits.js:1245:3)
    at Layer.handle [as handle_request](/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/colearnr/cl/webapp-v1.0.0-alpha1/node_modules/express/lib/router/route.js:131:13)

**Comment by prabhu** [comment]
Fixed with https://github.com/colearnr/colearnr/commit/61ec27ee239efc523e2ab99f580f11e17b934579
